language: python
python:
  - "3.6.6"
services:
  postgresql
addons:
  postgresql: '9.5'
# command to install dependencies
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt
before_script:
  - psql -c "CREATE DATABASE lme;" -U postgres
  - python lme.py
# command to run tests
script:
  - pycodestyle lme.py lme/app.py
  - pyflakes lme.py lme/app.py
  - pytest
#  - flake8 lme/app.py lme.py
#  - py.test --cov=pytocli tests/
#  - python -m doctest README.md
# after_success:
#  - coveralls